dist: xenial
sudo: true
language: python
addons:
  apt:
    update: true
before_install:
  - chmod +x install-gluu.sh
install:
  - sudo ./install-gluu.sh
script:
  - cd /install/community-edition-setup
  - ./setup.py
