dist: xenial
sudo: required
language: python
services:
  - docker
addons:
  apt:
    update: true
before_install:
  - chmod +x install-gluu.sh
  - chmod +x deploy.sh
  - chmod +x ./scripts/post-install.sh
  - chmod +x ./build/docker.sh
stages:
  - ci
  - oneclick
  - ubuntu
  - debian
jobs:
  include:
    - stage: ci
      name: Travis CI
      install:
        - sudo ./install-gluu.sh
      script:
        - sudo ./scripts/post-install.sh
    - stage: one-click
      name: One-Click Installer
      script:
        - ./build/docker.sh one-click installer
    - stage: ubuntu
      name: Xenial
      script:
        - ./build/docker.sh ubuntu xenial
    - stage: ubuntu
      name: Trusty
      script:
        - ./build/docker.sh ubuntu trusty
    - stage: debian
      name: Stretch
      script:
        - ./build/docker.sh debian stretch
    - stage: debian
      name: Jessie
      script:
        - ./build/docker.sh debian jessie
