dist: xenial
sudo: true
language: python
addons:
  apt:
    update: true
before_install:
  - chmod +x install-gluu.sh
  - chmod +x deploy.sh
  - chmod +x ./scripts/post-install.sh
install:
  - sudo ./install-gluu.sh
script:
  - ./scripts/post-install.sh
